global:
  metadata: 
    namespace: nginx

deployment:
  containers:
    - image: nginx
      tag: latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080

service:
  type: NodePort
  ports:
    - port: 8080
      targerPort: 8080

configmap:
  name: John Doe
  car: Kia
